# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a08e804752bc334d91917dcdccc2654a1708c2ceabae46fc5b479259781a827461e60217be4dcd9311e3c993403ec209915ed1f600d22152c8d499f6c047f1ed

test:
  secret_key_base: b6b588379aa8cda321acbe796580f1d91be484d1325624e2cbe890b3fb1d3daa96e30c89ce774027d99d6e89fc4c6e10f012086f8c47ff507cf611c2db234729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
